import Dogma from "../dogma/dogma";
import EntityManager from "../dogma/entityManager";
import Player from "./entities/player";
import "../style.css";
import PlayerTwo from "./entities/playerTwo";
const min = Dogma.createWorld("min");
const main = Dogma.createWorld("main");
const player = new PlayerTwo();
const playerTwo = new Player();
min.addSystem("Renderer");
EntityManager.addEntity(playerTwo);
EntityManager.addEntity(player);
Dogma.tickAll();
const wrap = EntityManager.wrapEntity(player.getID)!;
// EntityManager.removeEntity(player.getID);
min.removeSystem("Renderer");
Dogma.tickAll();
EntityManager.addEntityToWorld(wrap, "min");
Dogma.tickAll();
console.log(Dogma.getAllWorlds);
